OpenModelDB/open-model-database

- src/elements/markdown.module.scss
- src/elements/markdown.tsx
- src/styles/globals.scss
I chose a nicer-looking theme and added syntax highlighting to some inline code snippets.
> Improved markdown code elements

- .eslintrc.js
- src/elements/components/switch.module.scss
- src/elements/components/switch.tsx
- src/stories/Switch.stories.tsx
Simple implementation of a controlled switch.
> Added switch component

- src/elements/header.module.scss
- src/elements/header.tsx
- src/styles/globals.scss
This replaces the 2 button approach of the theme toggle with a single button that simply changes its icon.
> Simpler theme toggle

- src/pages/index.tsx
> Tag selector

- src/pages/index.tsx
- src/styles/globals.scss
- Model search bar
- Redesigns
- Placeholder images in each card
> Various Improvements

- package-lock.json
- package.json
- src/pages/models/[id].tsx
- src/styles/globals.scss
- Image carousel (dummy images for now)
- Description
- Download link
- Property table
haha JK added a slider
- Comparison slider
- thumbnail previews
> Model page start

- src/elements/components/download-button.tsx
- src/elements/components/image-carousel.tsx
- src/lib/util.ts
- src/pages/models/[id].tsx
- replace download `<button>` with `<a>`
- add more known hosts
- parse URL for unknown hosts
- Extract components
> Make download button <a> + parse url

- src/elements/components/model-card.tsx
- src/lib/react-util.tsx
Changes:
- I removed the "A X model" part because we already show the architecture as a tag.
- Properly format multiple authors.
> Improved model card

- src/pages/models/[id].tsx
Only issue is that it doesn't allow you to add or remove authors, if there are multiple. I don't see this as a huge issue at the moment though.
> Editable author on model page

- data/tags.json
- src/lib/architecture-data.ts
- src/lib/derive-tags.ts
- src/lib/license.ts
- src/lib/server/file-data.ts
- src/lib/server/fs-util.ts
- src/lib/util.ts
- src/pages/index.tsx
This adds a basic version of derived tags.
> Derived tags

- src/elements/components/model-card.tsx
- src/lib/util.ts
- src/pages/index.tsx
- src/pages/users/[id].tsx
Letting `ModelCard` take the whole model generally makes things easier.
> Let model card take the whole model

- src/pages/index.tsx
- src/pages/users/[id].tsx
```jsx
<div className="py-6">
<div className="mx-auto max-w-screen-2xl">
```
^ Those were pretty much useless because `PageContainer` already centers the page.
> Removed unnecessary divs from pages

- src/lib/search/score.ts
This improves the search by scoring 2 grams. This means that the search will not take token order into account. E.g. if the search query is "anime sharp", it will now score the text "I like anime sharp" higher than "sharp anime is good".
> Score 2 grams in search

- data/models/4x-BS-Deviance.json
- data/models/4x-BS-DevianceMIP.json
- data/models/4x-WaifuGAN-v3.json
- data/models/4x-eula-digimanga-bw-v1.json
- data/models/4x-eula-digimanga-bw-v2-nc1.json
- data/users.json
> Cleaned up user data

- src/pages/index.tsx
This PR adds a little button that is only visible on hover while in edit mode. It's essentially a debug button.
This is extremely useful for when you want to modify the DB in a quick but programmatic way. E.g. that's how I did #61.
> Added magic button

- src/elements/components/editable-label.tsx
- src/pages/models/[id].tsx
I didn't like the approach of #70, so...
> Make scale and number of channels editable

- package-lock.json
- package.json
- src/elements/components/download-button.tsx
- src/pages/models/[id].tsx
- tailwind.config.js
with edit mode its a bit ugly but it's functional at least
- Combines each resource's URL into a single download button with a mirror selection dropdown
- Allows the addition and removal of a URL to/from a resource
Doesn't allow adding new resources yet, as that will require a more complex UI
> Editable download resources + mirror selection

- data/tag-categories.json
Recorded tag categories according to @Kim2091's feedback.
> Reordered tag categories

- src/elements/tag-selector.module.scss
- src/elements/tag-selector.tsx
- src/pages/index.tsx
> Added simple tag selector

- src/elements/components/download-button.tsx
Changes:
1. Bring focus ring back. For some reason, focus rings were disabled everywhere, which is horrible for keyboard accessibility.
2. Only show dropdown menu when we are in edit mode or have more than one resource.
3. Moved "Hosted by X" text into the button.
Before:
After:
> Changed design of download button

- data/tag-categories.json
- src/elements/tag-selector.tsx
- src/lib/schema.ts
Right now, there are 2 types of purpose tags. Some describe what the model does (e.g. deblur, dedither, inpainting, general upscaling, restoration), and some describe what type of input data it expects (anime, manga, faces, pixel art).
This PR splits the old purpose category into 2 categories: subject and purpose.
> Split purpose into subject and purpose

- package-lock.json
- package.json
- src/elements/markdown.tsx
- src/elements/tag-selector.module.scss
- src/elements/tag-selector.tsx
- src/pages/_app.tsx
> Added tag tooltips

- src/elements/components/download-button.tsx
- src/pages/models/[id].tsx
> Fixed height of trash button

- src/elements/components/download-button-edit-popover.tsx
- src/pages/models/[id].tsx
> Add ability to add and edit resources

- src/elements/header.module.scss
- src/elements/header.tsx
- src/lib/hooks/use-web-api.tsx
I added a button to quickly switch between edit mode and how the website will look when deployed.
> Added edit mode toggle

- src/pages/index.tsx
> Show number of search results

- src/elements/components/model-card.module.scss
- src/elements/components/model-card.tsx
> Use actual images on model cards

- src/elements/header.module.scss
> Fix header z-index

- src/elements/components/image-carousel.tsx
> Fix image carousel overflow

- src/elements/header.tsx
A bit messy and hacky but it kinda works
> Add Model button

- package-lock.json
- package.json
- src/lib/hooks/use-search.ts
- src/lib/search/create.ts
- src/pages/index.tsx
Fixes #109.
I made a new version based on next's router.
> Store search query and tags in URL

- src/lib/hooks/use-search.ts
Guess who forgot to remove them :)
> Removed `console.log`s

- src/elements/components/editable-tags.tsx
> Search for tag when clicking on one

- src/elements/tag-selector.tsx
- src/pages/index.tsx
This makes the site feel snappier.
> No delay for simple tag selector

- src/elements/components/model-card-grid.module.scss
- src/elements/components/model-card-grid.tsx
- src/elements/components/model-card.module.scss
- src/elements/header.module.scss
- src/elements/page.module.scss
- src/elements/page.tsx
- src/pages/index.tsx
- src/pages/users/[id].tsx
- src/styles/globals.scss
Changes:
- Changed the break points for the model card grid. We now show more models on smaller screens.
- Made the arch + scale pseudo tags in the model card click through. They will no longer get in the way when trying to click on the model card.
- Made header buttons single line. They will no longer expand to multiple lines on small screens.
- Made the design of the page wrapper (the div that gives the centered page a slightly different bg color) more responsive.
- Changed the header line color in dark mode to be more visible.
- Improved text contrast for slogan in light and dark mode.
> Minor design improvements

- src/elements/components/image-carousel.tsx
> Only show left/right buttons in image carousel if there are >=2 images

- src/elements/components/scroll-to-top.module.scss
- src/elements/components/scroll-to-top.tsx
- src/elements/page.tsx
- src/pages/index.tsx
- src/pages/users/[id].tsx
Closes #107.
This button is added to the main page and user pages.
> Added Scroll To Top button

- src/elements/header.module.scss
> Made header slightly more transparent in dark mode

- src/elements/components/image-carousel.tsx
- src/hooks/useWindowSize.tsx
- src/pages/models/[id].tsx
it's not much, but it's a start
> Some mobile optimizations

- package-lock.json
- package.json
- src/elements/components/carousel/comparison.tsx
- src/elements/components/carousel/standalone.tsx
- src/elements/components/image-carousel-image.tsx
This was a lot easier than I was expecting it to be, and it worked pretty well.
> Better comparison box

- src/elements/components/carousel/comparison.tsx
- src/elements/components/image-carousel.module.scss
- src/elements/components/image-carousel.tsx
> Full-width images on mobile

- src/elements/tag-selector.tsx
- src/lib/hooks/use-is-touch.ts
They are super annoying on touch devices, so I removed them there.
> No tooltips on touch devices

- src/elements/components/model-card.tsx
Unfortunately, I can't get them to center
> Side-by-side comparisons in model card

- src/elements/components/header-drawer.tsx
- src/elements/header.module.scss
- src/elements/header.tsx
Not the best, but it's functional. Opted for a drawer instead of a popover.
> Mobile collapsed header

- src/elements/tag-selector.tsx
This changes the tag selector in the following ways:
1. If you switch from advanced to simple mode, it will now transform the current tag selection into something the simple tag selector can represent. It used to be that the selection was left unchanged, which caused the simple tag selector to not show forbidden tags and tags outside the simple categories.
2. If the tag selector is in simple mode, but has a tag selection that the simple mode cannot correctly represent, it will change to advanced mode.
Honestly, it's my bad for not making the tag selector behave like that in the first place.
> Change how the simple tag selector transforms tags

- src/elements/header.module.scss
- src/pages/index.tsx
> Added alpha notice

- src/pages/index.tsx
I made a mistake in #181. I adjusted the code for the order of results when the search query was updated, but I did not do this for the initial list of models that get displayed. So opening the search page still showed the old order.
> Fixed initial results order on search page

- data/models/1x-Compact-Pretrain.json
- data/models/1x-SuperUltraCompact-Pretrain.json
- data/models/1x-UltraCompact-Pretrain.json
- data/models/2x-Compact-Pretrain.json
- data/models/2x-SuperUltraCompact-Pretrain.json
- data/models/2x-UltraCompact-Pretrain.json
- data/models/4x-Compact-Pretrain.json
- scripts/validate-db.ts
- src/lib/model-props.ts
While working on #182, I noticed that some models had invalid resource sizes. This PR fixes those sizes and improves our DB validation to prevent this error in the future.
> Fixed invalid resources and improved validation

- src/elements/tag-view.module.scss
- src/elements/tag-view.tsx
- src/pages/tags.tsx
We can now add tags to a specific category and move tags around within categories.
> More editable tags

- src/elements/components/model-card.tsx
Changes:
- Always display remaining lines.
- Fixed purpose condition.
- Removed "Dataset: ". We have no descriptions with that string.
- Ignore category more directly.
> Improved model description fix

- src/elements/components/model-card.module.scss
- src/elements/components/model-card.tsx
> Fix blur effect

- data/models/2x-HDCube-Compact.json
- data/models/4x-HDCube2.json
- data/models/4x-HDCube3.json
This adds HDCube 2 and HDCube Compact.
Closes #127.
> Added missing HDCube models

- src/elements/components/image-carousel.tsx
> Fixed image thumbnail rounding

- src/elements/components/editable-markdown.tsx
- src/elements/tag-view.tsx
- src/pages/tags.tsx
This adds a way to sort tags and makes tag title and description easier to distinguish.
> Added tag sorting + minor improvements

- src/elements/components/image-carousel.tsx
- src/pages/models/[id].tsx
As discussed on discord. I called the props that resets the index `indexKey`.
> Reset image index on model id changes

- src/pages/models/[id].tsx
> Added license picker

- src/lib/server/file-data.ts
- src/pages/users.tsx
This adds a page that lists all users and allows us to edit them.
I also fixed a TODO with the file API
> Added users page

- src/elements/components/model-card.tsx
I described the cause of the bug on discord. The fix was to add an effect that looks at the natural width of LR and SR.
> Fixed pair model cards not being displayed

- src/elements/components/model-card.tsx
- src/lib/hooks/use-device-pixel-ratio.tsx
- src/pages/_app.tsx
> Ensure integer scaling for model card image pairs

- src/elements/components/editable-users.tsx
It's just a small link to the users page.
> Added link to edit users

- src/lib/util.ts
- src/pages/architectures.tsx
- src/pages/models/[id].tsx
- src/pages/tags.tsx
This PR adds a page to edit the architecture data we have. Editing archs will automatically update their tags.
It's ugly as hell, but it works.
> Added page for architectures

- src/pages/architectures.tsx
> Better architectures page

- data/models/4x-SPSR.json
- data/users.json
https://github.com/Maclory/SPSR
> Added official SPSR model

- .vscode/settings.json
- docs/faq.md
> Update FAQ page

- data/architectures.json
- data/models/2x-Waifaux-NL3-SRResNet.json
- data/tag-categories.json
- data/tags.json
As pointed out by @joeyballentine on Discord.
> Renamed "EDSR (SRResNet)" to "SRResNet"

- src/elements/tag-view.tsx
- src/lib/schema-util.ts
- src/pages/architectures.tsx
- src/pages/tags.tsx
Same as #250 and #262 but for tag ids.
> Strict tag ids

- src/pages/models/[id].tsx
See here: https://github.com/OpenModelDB/open-model-database/pull/264#discussion_r1267127524
> Don't write empty size array into the DB

- docs/contributing/models.md
After reviewing #264, I noticed that we don't explain this anywhere.
> Added "What's a model" section to contributing guide

- data/models/4x-muy4-035-1.json
I added the missing info to 4x-muy4-035-1. The download link also works now.
Thanks to @Kim2091 for getting the model file.
> Fixed info to muy4_035_1

- data/models/2x-AniScale.json
- data/models/2x-ParimgCompact.json
- data/models/4x-FatePlusCompact.json
- data/models/4x-Rybu.json
- data/models/4x-animerd-v1.json
- data/models/4x-ardo.json
All models that are hosted on discord are now also self-hosted.
> Self-host discord models

- docs/faq.md
Changes:
- Added direct link to download for chainner.
- Removed unused "Wiki" links.
> Improved FAQ program links

- src/lib/image-util.ts
When you paste in an imgbox.com link, it will now automatically extract the direct image link and thumbnail.
> Add support for extracting imgbox images

- data/models/4x-Normal-RG0-BC1.json
- data/models/4x-Normal-RG0-BC7.json
- data/models/4x-Normal-RG0.json
This has been long overdue. I added my 3 normal map models to the database.
> Added my 3 normal map models

- src/elements/components/scroll-to-top.module.scss
- src/elements/page.tsx
- tailwind.config.js
Changes:
- Pages with a wrapper (e.g. the home page) transition to the more compact design sooner. This is mostly just remove the padding around the wrapper. E.g.
- Reposition the scroll to top button sooner. I noticed that it was positioned awkwardly for some screen sizes.
> Minor design improvement

- src/elements/components/carousel/comparison.tsx
- src/elements/components/carousel/standalone.tsx
- src/elements/components/image-carousel-image.module.scss
- src/elements/components/image-carousel-image.tsx
- src/elements/components/image-carousel.tsx
Fixes #189
As discussed on Discord.
> Display image captions

- src/elements/components/download-button.tsx
- src/pages/models/[id].tsx
When there are multiple download buttons, it will now show the type of the resource.
> Show type of download

- src/elements/components/model-card.tsx
> Remove markdown links from model card

- data/models/4x-realesr-animevideo-v3.json
The thumbnail for that model sucked, so I used a different one.
> Better thumbnail for RealESR AnimeVideo v3

- src/pages/add-model.tsx
I added a list of common pretrained model to the Add Model page. Clicking on any of them will set it as the pretrained model. This should hopefully make it easier to find pretrained models.
> Show list of common pretrained models

- src/pages/models/[id].tsx
> More compact metadata table

- data/models/2x-Higurashi-v1-compact.json
Adds `2xHigurashi_v1_compact_270k.pth`
> Add Higurashi model

- docs/contributing/models.md
- invoke-spandrel.py
- src/elements/components/download-button-edit-popover.tsx
- src/lib/model-files.ts
- src/lib/util.ts
- src/pages/add-model.tsx
- src/pages/api/pth-metadata.ts
Changes:
- New ID input. The input now shows the full ID but only allows edits to the part after the scale. The ID will also default to the name unless set manually.
- Added direct input for pytorch models. This allows us to read metadata directly from the model file. Together with a download link for said model, it will even add the resource for the model.
This should make it a lot easier to add pytorch models.
> Improved Add Model page

- src/pages/tags.tsx
When changing tag implications in `tags.josn`, nothing changes for existing model, so add a button to update the tags of existing models.
> Add button to update tag implications

- src/pages/index.tsx
This changes the default sort to slightly prefer newer models.
> Prefer newer models by default

- .github/workflows/nextjs.yml
- next.config.js
- package.json
This fixes our build and unifies the `build` and `build-full` commands.
> Fixed the build after next v14

- data/models/1x-NormalMapGenerator-CX-Lite.json
> Add sample images for NormalMapGenerator-CX Lite

- data/models/4x-MinecraftAlphaUpscaler-with-Good-data.json
- data/models/4x-Minepack.json
- data/models/4x-PackCraft-v4.json
I'll fix the layout bug shortly.
> Add sample images for all pack.png models

- data/models/1x-DEDXT.json
- data/models/1x-DEPVR-Artifact.json
- data/models/1x-DEPVR.json
- data/models/1x-DM600-LUDVAE.json
- data/models/1x-DeRoqBeta-lite.json
- data/models/1x-Focus.json
- data/models/1x-Kim2091-DeJpeg-v0.json
- data/models/1x-MangaJPEGLQ.json
- data/models/1x-RoQ-nRoll.json
- data/models/1x-SheeepIt.json
- data/models/2x-GT-evA.json
- data/models/2x-GT-v2-evA.json
- data/models/2x-KemonoScale-v2.json
- data/models/2x-UniScale-CartoonRestore-lite.json
- data/models/2x-sudo-RealESRGAN-Dropout.json
- data/models/2x-sudo-RealESRGAN.json
- data/models/2x-sudo-UltraCompact.json
- data/models/2x-sudo-shuffle-cugan-9-584-969.json
Moves images from discord to imgbox. I also split many standalone images into LR SR pairs.
> Migrate discord images for all 1x and 2x models

- data/models/4x-AnimeSharp-lite.json
- data/models/4x-AnimeSharp.json
- data/models/4x-BooruGan-600k.json
- data/models/4x-BooruGan-650k.json
- data/models/4x-CountryRoads.json
- data/models/4x-DeCompress-Strong.json
- data/models/4x-DeCompress.json
- data/models/4x-FSMangaV2.json
- data/models/4x-Fabric-Alt.json
- data/models/4x-Fabric.json
- data/models/4x-FatePlusCompact.json
- data/models/4x-GameAI-2-0.json
- data/models/4x-Link.json
- data/models/4x-NMKD-YandereNeo.json
- data/models/4x-Rybu.json
- data/models/4x-SGI.json
- data/models/4x-SkyrimTex-v2-1.json
- data/models/4x-SkyrimTex-v2-Fabric.json
- data/models/4x-UltraSharp.json
- data/models/4x-UniScale-Restore.json
- data/models/4x-UniScaleV2-Moderate.json
- data/models/4x-UniScaleV2-Sharp.json
- data/models/4x-UniScaleV2-Soft.json
- data/models/4x-Valar.json
- data/models/4x-VolArt.json
- data/models/4x-anifilm-compact.json
- data/models/4x-animerd-v1.json
- data/models/4x-ardo.json
This migrates the rest of our discord images.
> Migrate discord images for all 4x models

- scripts/thumbnails.py
Changes:
- Use thread pool to download images from cache (website). This makes thumbnail generation ~10x faster. From 45sec to 4.6sec on my machine.
- Don't log when downloading images from cache.
- Flush logs. This should fix the issue that logs don't show up immediately in GH CI.
> Improved thumbnail script logging and performance

- data/models/4x-Frankendata-FullDegradation-SRFormer.json
> Fix scale of Frankendata_FullDegradation_SRFormer

- src/elements/components/download-button.tsx
- src/lib/download-util.ts
This is preparation for a feature I'm still working on.
> Extract download utility out into its own file

- data/models/8x-Arzenal-v1-1.json
- data/models/8x-MS-Unpainter-De-Dither.json
- data/models/8x-MS-Unpainter.json
I had to pay 5€ to finally download those models, but it was well worth it. With this, all models now have working download links and SHA256 hashes.
> Make public downloads available for the last 3 models

- data/models/8x-BoyMeBob-Redux.json
I messed up the images when I added that model, so I fixed it in this PR.
> Fix images for 8x BoyMeBob Redux

- data/models/1x-NMKD-Jaywreck3-Lite.json
- data/models/1x-NMKD-YandereInpaint.json
- data/models/1x-NMKD-h264Texturize.json
- data/models/1x-sudo-inpaint-PartialConv2D.json
- data/models/2x-DeGif.json
- data/models/2x-NMKD-YandereNeo.json
- data/models/4x-NMKD-PatchySharp.json
- data/models/4x-NMKD-Siax-CX.json
- data/models/4x-NMKD-UltraYandere-Lite.json
- data/models/4x-NMKD-UltraYandere.json
- data/models/4x-NMKD-YandereNeo-Superlite.json
- data/models/4x-NMKD-YandereNeo-XL.json
- data/models/4x-NMKD-YandereNeo.json
- data/models/8x-NMKD-Typescale.json
I added images for many models by NMKD. Those images are largely taken from NMKD's icedrive, although I did run the models on a few of them myself.
I also added more tags to a few models.
> Add images for many NMKD models

- data/models/2x-spanx2-ch48.json
- data/models/4x-spanx4-ch48.json
Changes:
- Self-hosted downloads for official span models
- Added Research tag to models
- Added link to span repo
> Direct download link for official span models

- src/pages/add-model.tsx
> Properly trim description on Add Model page

- scripts/validate-db.ts
- src/lib/model-props.ts
This adds the basics for more involved validation.
> Add custom validators

- src/elements/components/download-button-edit-popover.tsx
- src/elements/components/download-button.tsx
- src/lib/schema.ts
We can now add `.safetensors` files to models.
> Add support for safetensors resources

- data/models/2x-AnimeJaNai-HD-V3-Compact.json
- data/models/2x-AnimeJaNai-HD-V3-SuperUltraCompact.json
- data/models/2x-AnimeJaNai-HD-V3-UltraCompact.json
- data/models/4x-IllustrationJaNai-V1-DAT2.json
- data/models/4x-IllustrationJaNai-V1-ESRGAN.json
Adds IllustrationJaNai V1 models to the database, and adjusts thumbnail order for the AnimeJaNai HD V3 models.
> Add IllustrationJaNai V1 Models

- .github/workflows/frontend.yml
- .github/workflows/nextjs.yml
Nothing fancy. I just used prettier to format our workflow files.
I need this for another PR, so I'm going to merge this of CI passes.
> Format GitHub YAML files

- data/models/2x-AniScale.json
- data/models/2x-DigitalFilmV5-Lite.json
- data/models/2x-ParimgCompact.json
- data/models/2x-cainREALTIME.json
- data/models/2x-cainliteanime.json
- data/models/4x-FatePlusCompact.json
- data/models/4x-Rybu.json
- data/models/4x-animerd-v1.json
- data/models/4x-ardo.json
- data/models/4x-eula-anifilm-v1.json
- data/models/4x-eula-digimanga-bw-v1.json
- data/models/4x-eula-digimanga-bw-v2-nc1.json
- data/models/4x-muy4-035-1.json
This removes all (now dead) discord that already have a mirror.
> Remove unnecessary discord links

- data/models/4x-DWTP-DP-dat2-beta.json
- data/models/4x-DWTP-DS-dat2-v1.json
- data/models/4x-DWTP-DS-dat2-v3.json
- data/models/4x-DWTP-ds-esrgan-5.json
- data/models/4x-WTP-ColorDS.json
- data/models/4x-WTP-UDS-Esrgan.json
- data/models/4x-eula-digimanga-MiA-65k.json
> Self-host remaining discord models

- data/models/1x-PBRify-Height.json
- data/models/1x-PBRify-NormalV3.json
- data/models/1x-PBRify-RoughnessV2.json
- data/models/4x-PBRify-UpscalerSPANV4.json
- data/models/4x-SwinIR-S-Pretrain.json
Closes #414 
Closes #415 
Closes #416 
Closes #417 
Closes #418
> Add kim's model requests

- data/models/1xSkinContrast-HighAlternative-SuperUltraCompact.json
- data/users.json
> Add request 427

- data/models/2x-Pooh-V4.json
- data/models/Pooh-V4.json
- data/users.json
> Add request 429

- data/architectures.json
- data/collections.json
- data/models/4x-DAT2-mssim-Pretrain.json
- data/models/4x-PBRify-UpscalerDAT2-V1.json
- data/models/4x-PBRify-UpscalerSIR-M-V2.json
- data/models/4x-RealPLKSR-Pretrain-V4.json
- data/models/4x-RealPLKSR-dysample-pretrain.json
- data/tag-categories.json
- data/tags.json
> Add my models

- data/models/4x-AnalogFrames-1-0.json
- data/models/4x-NumericFrames-2-0.json
- data/models/4x-NumericFrames-2-1-Aggressive.json
- data/models/4x-NumericFrames-2-5.json
Closes #444 
Closes #443 
Closes #442 
Closes #441
> Add model requests

- data/models/4x-PBRify-UpscalerSPANV4.json
> Fix broken model link

- src/elements/header.tsx
> Fix Discord invite links
