- src/elements/components/link.tsx
- src/elements/header.tsx
- src/elements/markdown.tsx
- src/elements/side-bar.tsx
- src/pages/api/model-id.ts
- src/pages/api/models.ts
- src/pages/api/tag-id.ts
- src/pages/api/tags.ts
- src/pages/api/user-id.ts
- src/pages/api/users.ts
- src/pages/docs/[[...slug]].tsx
- src/pages/index.tsx
- src/pages/models/[id].tsx
- src/pages/users/[id].tsx
- tsconfig.json
I noticed that Joey changed an absolute import to a relative one in #11, and I agree. I only used absolute paths because that's what VSCode auto import used. 
Removing `baseUrl` from `tsconfig.json` makes all absolute paths invalid, so we have to use relative paths now. `baseUrl` was added by nextjs btw, so I won't miss it.
> No more absolute imports

- package-lock.json
- package.json
- src/elements/components/switch.module.scss
- src/elements/header.module.scss
- src/elements/side-bar.module.scss
- src/pages/palette.tsx
- src/styles/colors.scss
- src/styles/globals.scss
- src/styles/theme.scss
This PR sets the tone for how light and dark mode will work.
Firstly, colors are done via SCSS. We may add theme to tailwind later, but SCSS will be the source of truth. That being said, the color palettes I created are heavily inspired by tailwind's and even include tailwind's neutral palette.
Themes are done in SCSS either via semantic colors or the `themed` mixin. Semantic colors are CSS variables defined in `globals.scss`. They describe general concepts that can be reused across components. 
The `themed` mixin is the backbone of the whole theme system. It's used like this:
```scss
@include themed using ($t) {
prop: t($t, light value, dark value);
}
```
`$t` is the name of the current theme (currently either "light" or "dark"). `t($t, light, dark)` is a selector function that returns …
> Added new theme system

- src/pages/_document.tsx
- src/styles/theme.scss
PR always sets the `data-theme` attribute, even if the user has not previously selected a theme, in which case the attribute is initialized based on system preferences. Since the attribute is now the source of truth for the current theme, the `themed` SASS mixin also got simpler.
> Always set `data-theme` attribute

- src/elements/components/download-button.tsx
- src/elements/components/link.tsx
- src/elements/components/model-card.tsx
- src/elements/components/searchbar.tsx
- src/pages/index.tsx
- src/pages/models/[id].tsx
- Fixed incorrect usage of `key`.
- Removed unnecessary `React.Fragement`s.
- Proper usage of `a` and `Link` (our).
- Fixed model card using internal and external links inconsistently. They are all internal now.
- Fixed `SearchBar` allowing optional `value`. If `value` is undefined, the underlying `input` is uncontrolled and switching from uncontrolled to controlled is not allowed by React.
@Joey about links: The idea of my `Link` component was to have a link component that we control and that handles internal vs external links. This difference needs to be handled because NextJS uses client side routing, so it's `Link` (from `next/link`) is special and cannot be exchanged with a regular `a` lightly.
> Minor fixes

- data/tags.json
- src/elements/components/model-card.tsx
- src/lib/hooks/use-tags.ts
- src/lib/hooks/use-users.ts
- src/lib/static-data.ts
- src/pages/index.tsx
- src/pages/users/[id].tsx
Model names still have to be cleaned up, but that's for later.
`useTags` and `useUsers` are hooks, because their implementation will likely change in the future. I expect that we will likely have to refetch data in edit mode in the future, so I made these hooks for that.
> Show names for tags, users, and models

- package-lock.json
- package.json
- src/lib/data-api.ts
- src/lib/hooks/use-models.ts
- src/lib/server/file-data.ts
- src/lib/web-api.ts
- src/pages/api/mutation-sse.ts
- src/pages/index.tsx
- src/pages/users/[id].tsx
This PR adds SSE to make the backend tell the frontend about mutations to the underlying database. This includes mutations done by the frontend and mutations done my manual edits (e.g. by directly editing data files in an editor). As a result, the data shown in the frontend is now synchronized, so when you make an edit in one page, those changes are reflected everywhere in real time.
Detecting manual edits to files is done using chokidar. I have seen some problems with chokidar and NextJS hot reloading, but it seems to mostly work fine now.
> Reload model data on mutation

- data/tag-categories.json
- data/tags.json
- src/elements/components/editable-label.module.scss
- src/elements/components/editable-label.tsx
- src/elements/components/editable-markdown.module.scss
- src/elements/components/editable-markdown.tsx
- src/elements/tag-view.module.scss
- src/elements/tag-view.tsx
- src/lib/data-api.ts
- src/lib/hooks/use-tags.ts
- src/lib/schema.ts
- src/lib/server/file-data.ts
- src/lib/static-data.ts
- src/lib/util.ts
- src/lib/web-api.ts
- src/pages/api/tag-categories.ts
- src/pages/models/[id].tsx
- src/pages/tags.tsx
This PR adds tag categories and a simple page to edit tags.
Tag categories are a list of tags with a name. They will be used for implementing the tag selector I proposed a while back.
That tags page itself is a simple list of all tag categories with their respective tags. All tag names, tag descriptions, and tag category names are editable.
To make these properties editable, I added 2 new components: `EditableLabel` and `EditableMarkdownContainer`. Both components are thin wrappers around their underlying components (`<span>` or `MarkdownContainer`), but switch to a different component while editing. This makes these components really easy to use, so I used them in model pages as well.
> Added tag categories

- src/elements/markdown.tsx
I noticed that model pages took longer to load since #49. It turned out that `react-syntax-highlighter` adds a bunch of Prism languages, so just importing `react-syntax-highlighter` took 1sec at the start of every page load. This is because Prism languages are eagerly evaluated before being added. This is a limitation of Prism (v1).
My solution was to simply import only the Prism languages we need. This brought down the import time from 1sec to basically nothing.
> Faster markdown component loading

- src/elements/components/link.tsx
- src/elements/components/model-card.module.scss
- src/elements/components/model-card.tsx
This PR includes 3 changes:
- Simplify DOM tree, remove unnecessary tailwind classes, and extract some classes out into SCSS.
- Make the card thumbnail not focusable via keyboard. This makes keyboard navigation easier.
- Change some colors for better readability.
The optimization stuff is the main change. I noticed that the main page has grown to 1MB (just HTML!!!). The culprit is `ModelCard` which generates a bunch of HTML. So I optimized `ModelCard` and got the size down to "only" 881KB (17% less). Still not great, but better.
> Optimized ModelCard

- src/lib/site-data.ts
- src/lib/web-api.ts
Fixes this:
Since we don't deploy API routes, we know that this is going to always fail, so I added a little check to skip the request.
> Don't try to access the backend API when deployed

- src/elements/tag-selector.tsx
- src/lib/hooks/use-is-client.ts
Due to hydrations, tooltips must be mounted only client-side.
> Fixed tooltips

- package-lock.json
- package.json
As mentioned in https://github.com/ReactTooltip/react-tooltip/issues/972, next@13.2.5-canary.22 fixes the bug that prevent react-tooltip from working. It's a pre-release of nextjs, but it makes everything work. So I propose that we use 13.2.5-canary.22 for now and update to 13.2.5 proper or 13.3.0 as soon as it comes out. (Looking at the version history, it seems likely that they'll skip 13.2.5 and go for 13.3.0.)
> Tooltip fix for real

- src/lib/server/api-impl.ts
- src/lib/server/file-data.ts
Changes:
1. Fixed the condition for changing the IDs of every collection except for models.
2. Better errors in API routes. We will now log errors (revolutionary) and send the full error stack back to the frontend.
> Fixed change ID implementation & better errors for API routes

- data/models/4x-2C2-ESRGAN-Nomos2K.json
I added the missing model data since chainner can now read this model. I also updated the description and gave the "Pretrained" tag instead of "General upscaler".
> Added data for 2C2-ESRGAN model

- src/elements/components/editable-tags.module.scss
- src/elements/components/editable-tags.tsx
- src/elements/components/model-card.module.scss
- src/elements/components/model-card.tsx
- src/lib/hooks/use-update-model.ts
- src/pages/models/[id].tsx
This PR adds a component for editable tags. It's basically a pop over that allows you to quickly add/remove tags by simply clicking them. I also moved tags in model pages to be more consistent with model cards.
Model cards also allow editing tags, which means that we can edit tags directly from the search page.
> Editable tags

- src/elements/components/editable-users.tsx
- src/pages/models/[id].tsx
Changes:
- Use the same link color as model card.
- Use `joinList` to join multiple authors, just like model card.
- Make the difference between edit and non-edit mode more obvious.
> Improvements to editable users

- src/elements/components/model-card.tsx
Model cards are quite expensive in edit mode, which can cause noticeable lag. Memo-ing them stops this lag.
> Memo model card

- data/tag-categories.json
- data/tags.json
- src/elements/tag-selector.tsx
- src/lib/derive-tags.ts
- src/lib/schema.ts
This adds helper tags. They are intended to flag models that are points of interest for maintainers. Helper tags are only visible in edit mode.
> Added edit-only helper tags

- package-lock.json
- package.json
`@next/font` is deprecated in favor of `next/font`. We weren't using `@next/font` anyway, so nothing is lost.
> Removed `@next/font`

- data/models/8x-MS-Unpainter-De-Dither.json
- data/models/8x-MS-Unpainter.json
While I can't download those models, pcloud still has this information on the page, just invisible. Just open dev console and print the global variable `publinkData`.
> Added file size for MS Unpainter models

- src/lib/hooks/use-models.ts
This makes `useModel` slightly more efficient by diffing with the previous models. This enables memoizing for unchanged models.
> More efficient `useModels`

- .github/workflows/nextjs.yml
We have to consider our JSON files as well in the cache key. Otherwise, database-only changes won't trigger a full rebuild.
> Fixed next build hash

- src/elements/components/model-card.module.scss
- src/elements/components/model-card.tsx
Very long titles that are one word (=no spaces) overflowed when the model card was small enough, so I fixed that.
> Better word breaking for model card titles

- src/elements/components/model-card.tsx
I made a small mistake when adding lazy loading. `LazyLoadComponent` needs a placeholder and uses an empty `<span>` by default. 
```html
<div class="model-card_modelCard__QF9dZ border-gray-300 bg-white shadow-lg hover:shadow-xl dark:border-gray-700 dark:bg-fade-900">
<span class="" style="display:inline-block"></span>
</div>
```
This results in roughly 350 unnecessary DOM elements on the main page. So this PR changes that to use the model card wrapper instead. We need the wrapper anyway, so might as well use it as the placeholder.
> More efficient lazy model card

- src/lib/hooks/use-search.ts
When the user made an input after the URL has been updated (reflected the current search parameters) but before the `useEffect` to update the search parameters based on the URL, then this input would be ignored. This is hard to reproduce, but it actually happened to me a few times.
The fix is to simply ignore any URL updates that we caused ourselves.
> Fixed rare useSearch race condition

- src/elements/tag-selector.tsx
While making #150, I noticed that tag tooltips get in the way. So I made them click-through.
> Make tag tooltips click-through

- data/models/1x-DeBink-Lite.json
- data/models/1x-sudo-inpaint-PartialConv2D.json
- data/models/2x-sudo-rife4-testV1.json
I found 3 invalid images. 2 were videos and the last one is somewhat dead. The last one was for sudo's inpaint model. Sudo has an example image hosted by pcloud, and it seems like pcloud does not like direct image links. Pcloud download links expire after a few hours, so we can't directly link to anything on there.
> Fixed 3 images

- src/elements/components/download-button.tsx
I made it so that the download button simply says "Download" when we are the hoster. I don't think there's a reason to announce that we are hosting a particular file, since we want that to become the default.
> Simpler download button

- src/elements/header.module.scss
This adds a gradient to the header's background. From top to bottom, it used the regular background with 100% alpha and transitions to transparent. This has the effect that whatever is behind the header gets faded out. This not only looks nice, it also prevents slight flickering caused by blurring the backdrop, and it makes header elements more readable.
> Add slight gradient to header background

- src/pages/models/[id].tsx
This makes the padding of the model pages consistent with the search page. This changes also saves space on mobile.
> Removed unnecessary top padding from the model pages

- src/pages/models/[id].tsx
This makes long model names look more compact on mobile.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20878432/235239909-ac523e73-7417-42f7-8937-2b0d23380b96.png) | ![image](https://user-images.githubusercontent.com/20878432/235239916-3e08679d-afb3-4fc1-8896-0ed700a79af2.png) |
> Improved line height of model name

- src/elements/components/header-drawer.tsx
Changes:
- Use pointer cursor for all buttons. This makes the menu easier to understand for people on desktop with small screen and/or large DPI scaling.
- Made `aria-controls` work. Since the menu drawer was conditionally rendered, `aria-controls` pointed to an element that didn't exist and was therefor invalid. So I made the drawer always render and just set it to `display: none`. I also changed the ID.
- Added `aria-label` to the button that opens the mobile menu.
- Removed focus-ring styles. @joeyballentine, I do not know where you got them from, but please don't use them again. They just remove the focus ring, which makes keyboard navigation very difficult.
> Minor improvements for the mobile menu

- src/elements/tag-selector.module.scss
- src/elements/tag-selector.tsx
I made the design of the advanced tag selector a little more dense to use the available screen space better. This allows to finally see all tags on my laptop without zooming out.
Before:
After:
> Denser advanced tag selector

- src/elements/components/header-drawer.tsx
I saw this warning and fixed it. The icon still looks exactly the same.
> Fixed react warning about path props

- src/lib/search/search-index.ts
- src/pages/index.tsx
Pretrained models are only really interesting for models trainers but not so much for regular users. So I every so slightly reduced the search score of all pretrained models. This has the effect that they will be last in the list of search results if there is no search text. If the user searches for a model by name, this de-buff is pretty much irrelevant.
> De-buff pretrained models in search

- src/lib/hooks/use-models.ts
- src/pages/tags.tsx
Because I passed a new empty object to `useModels` every time, `useModels` always returned no models.
> Fixed tag usage on tags page

- data/tag-categories.json
- data/tags.json
- src/lib/derive-tags.ts
I noticed that a few models do not have tags, so I added a helper tag to more easily find these models. This should help us to resolve\ #186.
I also combined the "Needs date" and "Invalid date" tags. I originally made them 2 tags, because we had lots of both in the beginning. With dates all cleared up now, one tag will suffice.
> Added new helper tag for tags and combined date helper tags

- src/elements/tag-selector.module.scss
- src/elements/tag-selector.tsx
Resolves #106.
The "Clear all tags" button is only visible in advanced mode, because it's pretty much useless in simple mode.
> Added a button to clear all tags and a link to edit tags

- src/elements/components/model-card-grid.tsx
- src/elements/components/model-results.module.scss
- src/elements/components/model-results.tsx
- src/lib/sort-models.ts
- src/pages/index.tsx
Resolves #182.
This PR adds the `ModelResults` which can sort models by arbitrary criteria. Right now, I added sorting by relevance, date, scale, and size. The default sort mode is "relevance", which doesn't sort the models at all, because `ModelResults` assumes that models are sorted by relevance to begin with.
I'm not really happy with the design of the dropdown, but I can't think of something better rn.
> Added option to sort model in search page

- src/elements/components/model-results.module.scss
- src/elements/components/model-results.tsx
When I changed the breakpoint for mobile, I forgot to update it for the alignment of the dropdown too. The dropdown is right aligned on large screens and left aligned on small ones.
> Fixed sort dropdown alignment

- src/elements/components/model-card.module.scss
- src/elements/components/model-card.tsx
I think it gives it a nice effect. It only gets applied to paired images, the standalone and "no image" ones are like they were before. I also had to shift the images up to get them approximately where they were positioned before this change pushed them down a bit.
> Add blur effect to paired image cards

- src/elements/components/model-card.tsx
This maybe fixes an issue I noticed. On mobile, you'll sometimes see one pixel of the text on the fourth line. The description div already has `overflow: hidden`, but it also has padding. So I replaced the padding with margin to make sure the fourth line is no longer juuust visible because of padding.
> Replace padding with margin to hide overflow

- src/elements/components/header-drawer.tsx
In #174, I made the header drawer's contents always render. This fixed a lighthouse issue, but also increased the HTML we have to ship. In this PR, we only render the contents of the drawer when opened, while still always rendering the container `div`. This reduced the HTML we ship and doesn't cause lighthouse issues.
> Only render mobile header contents when open

- src/elements/components/download-button-edit-popover.tsx
Checksum hexadecimals should always be lower case for consistency.
> Always lower-case sha256

- src/elements/header.tsx
- src/pages/add-model.tsx
Closes #59.
The new page is ugly as the night, but it's functional. The basic workflow is that you select the pretrained model (if possible), the name part of the id, and the model's scale. We will create a new model and redirect to the model's page. Since we know the pretrained model in many cases, we can fill in arch-related properties automatically.
> Add model page

- src/elements/components/model-card.module.scss
This stretches the hitbox of model card titles up to touch the hitbox of the model card image. This eliminates the gap between title and image.
> Improved hitbox for card title links

- src/elements/components/image-carousel.tsx
When using similar models to go to another model, `ImageCarousel` retains the state of the previous model. This caused the image index to be out of bounds sometimes. I fixed this by adding a new effect that looks for image changes.
> Fixed OoB image index

- src/elements/markdown.module.scss
I noticed that long Markdown links would dictate the page width on mobile because they did not break. This PR fixes that. I also made this effect always present, not just on small screens as before.
> Break long markdown elements

- src/pages/add-model.tsx
After adding a new model, we would see a 404 page before NextJS updated and showed us the model page. This PR fixes this by fetching the page before navigating to it. I also add state to track whether we are currently adding a model.
> Fixed 404 after adding model

- src/elements/components/image-carousel-edit-popover.tsx
- src/lib/schema.ts
- src/lib/server/file-data.ts
See #189.
This PR adds support for captions in model data and allows us to edit them. 
However, I didn't know how to best display captions to our users. I think that this could be done is follow-up PRs.
---
I also fixed the incorrect ids of some input elements.
> Added partial support for captions

- data/models/1x-DeRoqBeta-lite.json
- data/models/1x-Focus.json
- data/models/1x-Kim2091-DeJpeg-v0.json
- data/models/1x-MangaJPEGLQ.json
- data/models/1x-RoQ-nRoll.json
- data/models/1x-SheeepIt.json
- data/models/2x-KemonoScale-v2.json
- data/models/2x-NMKD-YandereNeo.json
- data/models/2x-anifilm-compact.json
- data/models/4x-AnimeSharp-lite.json
- data/models/4x-AnimeSharp.json
- data/models/4x-BooruGan-600k.json
- data/models/4x-BooruGan-650k.json
- data/models/4x-CountryRoads.json
- data/models/4x-DeCompress-Strong.json
- data/models/4x-DeCompress.json
- data/models/4x-FSMangaV2.json
- data/models/4x-Fabric.json
- data/models/4x-GameAI-2-0.json
- data/models/4x-Link.json
- data/models/4x-NMKD-YandereNeo.json
- data/models/4x-SGI.json
- data/models/4x-UltraSharp.json
- data/models/4x-UniScale-Restore.json
- data/models/4x-UniScaleV2-Moderate.json
- data/models/4x-UniScaleV2-Sharp.json
- data/models/4x-UniScaleV2-Soft.json
- data/models/4x-VolArt.json
- data/models/4x-anifilm-compact.json
This PR replaces many (but not all) of the standalone captioned comparison images with paired variants with the captions cropped out. While I was replacing them, I noticed that there were a few that my script missed. I will refine the script to get the rest once this is merged.
> Replace standalone captioned comparison images with paired ones

- data/models/1x-DEPVR-Artifact.json
- data/models/1x-DEPVR.json
- data/models/1x-GainRESV3-Natural.json
- data/models/1x-GainRESV4.json
- data/models/2x-90s-cartoon-v1.json
- data/models/2x-AniScale.json
- data/models/2x-AnimeJaNai-Standard-v1-Compact.json
- data/models/2x-AnimeJaNai-Standard-v1-SuperUltraCompact.json
- data/models/2x-AnimeJaNai-Standard-v1-UltraCompact.json
- data/models/2x-AnimeJaNai-Strong-v1-Compact.json
- data/models/2x-AnimeJaNai-Strong-v1-UltraCompact.json
- data/models/2x-GT-v2-evA.json
- data/models/2x-HFA2kCompact.json
- data/models/2x-ParimgCompact.json
- data/models/4x-FatePlusCompact.json
- data/models/4x-HFA2k.json
- data/models/4x-LSDIRCompact-v2.json
- data/models/4x-LSDIRCompact.json
- data/models/4x-LSDIRCompactC.json
- data/models/4x-LSDIRCompactC3.json
- data/models/4x-LSDIRCompactN.json
- data/models/4x-LSDIRCompactR.json
- data/models/4x-LSDIRCompactR3.json
- data/models/4x-Nomos8kSC.json
- data/models/4x-Rybu.json
- data/models/4x-animerd-v1.json
- data/users.json
I added all models released in the release channel on EE since 2023-01-18 (2x_Futsuu_Anime) except for sudo_shuffle_cugan_9.584.969.pth and DM600_LUDVAE. LUDVAE is a model for adding noise, which is something our target demo probably isn't interested in. Shuffle cugan just doesn't work with chainner, so I'm just skipping it.
> Added models released since

- src/elements/components/image-carousel-edit-popover.tsx
- src/lib/image-util.ts
This PR makes it easier to add sample images. I added the following features:
- Relevant inputs (LR, and URL) are auto focused.
- The links of standalone images are parsed. This mainly means that we can now do "Copy image link" in discord, paste the link, and it will automatically figure out the discord CDN link from the (typically sized) discord media link.
- The links of paired images are parsed to automatically extract LR and SR from the linked site. Right now, it supports Imgsli and SlowPic. This makes it super easy to add image pairs. You can simply select the images you want to compare on Imgsli, paste in the URL, and that's it.
> Easier sample image input

- src/elements/components/download-button-edit-popover.tsx
- src/lib/server/file-data.ts
- src/pages/api/save-model.ts
- src/pages/models/[id].tsx
This adds a little "Get info from file..." button to the resource edit pop over. When clicked, it opens a file dialog for model files. Upon selecting a model file, it will fill in the size, SHA 256, and platform. This makes it pretty easy to add new resources now.
It will also save the model under the correct model id in the data directory. This will be important later when we add a workflow for generating upscales of standard images.
> Get resource info from file

- data/models/1x-ITF-SkinDiffDDS-v1.json
- data/models/1x-ITF-SkinDiffDetail-Lite-v1.json
- data/users.json
Changes:
- Removed discord numbers from id of user "intheflesh". This is consistent with other users.
- Merged "tg" and "torrentguy".
- Removed "laeris". This user does not have any models. On the old model db, Skyrim Misc and Skyrim Wood both link to the same model, so I only added Skyrim Misc by Deorder.
> Updated users

- src/elements/components/carousel/comparison.tsx
- src/styles/globals.scss
This makes the hitbox for the comparison slider handle larger than it visually appears. This makes it a lot easy to actually hit the damn thing, especially on mobile.
Unfortunately, `ReactCompareSlider` does not have an option for this aside from replacing the whole handle, so I added a bit of hacky CSS.
> Larger compare slider handle

- data/architectures.json
- data/models/4x-2C2-ESRGAN-Nomos2K.json
- data/tag-categories.json
- data/tags.json
Changes:
- Renamed "2c2 ESRGAN" to "ESRGAN 2c2".
- Added more compatibility data. Progress toward #56.
- Fixed RIFE being classified as an image architecture.
> More arch data

- package.json
The dev server used to use 3000, which is also used by forge, so I could work on this website and have chainner open at the same time. So I changed the port of the dev server.
> Use different port for dev sever

- src/pages/models/[id].tsx
It will now use large embeds when we have an image for the model and small embeds otherwise.
> Only use a large card when we have an image to show

- data/models/2x-AniScale.json
from the author:
> hmm it looks like the page currently says it's esrgan
can someone please fix it, as it's a compact model?
> Fix aniscale architecture

- data/models/4x-Deoldify.json
- src/pages/models/[id].tsx
- src/styles/globals.scss
This fixes the text overflow we see on DeOldify's page. I also added spaces to the dataset description itself for better formatting.
> Added break words to dataset string

- src/elements/components/editable-label.tsx
- src/pages/users.tsx
This fixes a minor bug I noticed in #250. `EditableLabel` (EL) assumes that its value is written into the database as is. But we canonicalize user ids first to prevent invalid data. This can lead to 2 situations:
1. The user presses Enter, EL displays the text they just entered, and that text is then updated to the canonicalized version ~3sec later.
2. The user presses Enter, EL displays the text they just entered, and canonicalized version of the text is the same as the old id, which causes EL to never update and keep displaying the wrong user id.
Neither of those situations are ideally but 2 is really bad.
This PR fixes that by allowing `onChange` to return a string. `onChange` handlers that transform the entered string can now return the transformed version, which causes EL to …
> Allow `onChange` transformation in `EditableLabel`

- .github/workflows/nextjs.yml
The doc pages use git history to figure out they have been last modified. This timestamp is then displayed on the website.
However, `actions/checkout@v3` doesn't checkout git history by default (for good reason), so it caused all our doc pages to have the same last modified date. This PR fixes that by configuring the action to fetch git history as well.
> Fixed deployment checkout not including history

- src/elements/markdown.module.scss
- src/elements/markdown.tsx
- src/pages/docs/[[...slug]].tsx
This fixes 2 bugs:
- When linking to any `foo/index.md`, the relative compiled links where to `foo/index`, which doesn't exist because it's just `foo`.
- When linking to other pages from any `foo/index.md`, the relative links were wrong because the page is just `foo`, which is one directory level up.
I also improved the scrolling behavior of links. They will no longer be behind the header.
> Fixed relative links in doc pages

- docs/contributing/documentation.md
- docs/contributing/github.md
- docs/contributing/index.md
- docs/contributing/models.md
- docs/manifest.json
This adds a bunch more docs about contributing. I explained:
- The general workflow for contributing.
- Project setup.
- How to contribute docs.
- How to contribute models.
I wrote all of it with non-programmers in mind. People with no coding experience should be able to follow along somewhat. I want to make it even more newcomer-friendly in the future, but we'll need things like #255 for that.
> More contributing docs

- src/elements/side-bar.tsx
I found that the really small buttons to collapse sidebar items were not only close to useless, but they could even be harmful. It's not obvious that the small icons are buttons, so users might accidentally click them, collapsing child items, and not know how to expand them again.
> Disable collapsing items in sidebar

- data/models/4x-Wood-BC1.json
- data/users.json
This adds my BC1 wood model. It's a model I made some while ago to upscale wood textures. It kinda sucks in many ways, but it adds nice high frequency wood textures everywhere.
> Add 4x-Wood-BC1.pth

- src/elements/components/model-card.tsx
Added a thumbnail to paired images resulted in the model card being messed up.
I fixed this.
> Removed thumbnail for paired images in model card

- data/models/1x-FrankenMapGenerator-CX-Lite.json
- data/models/1x-NormalMapGenerator-CX-Lite.json
- data/models/1x-normals-generator-general.json
- data/tag-categories.json
- data/tags.json
Changes:
- Added descriptions to all Subject tags.
- Added descriptions to all Platform tags.
- Removed the "Game Texture Maps" tag. I think I was the one that added this tag, but even I can't remember what the difference between this tag and "Game Textures" is. So I removed the tag to make things easier.
> More tag descriptions and removed "Game Texture Maps"

- src/elements/components/image-carousel.tsx
What the title says. When there's only a single image, then the controls don't do anything, so I hid them in non-edit mode.
This PR is best reviewed while hiding whitespace changes.
> Don't show carousel controls if there's only a single image

- src/elements/components/editable-label.module.scss
- src/elements/components/editable-label.tsx
Where long model names were not properly broken on mobile. They now are.
> Properly break model names

- src/pages/models/[id].tsx
We displayed Training OTF as a switch before, which wasn't right, because the value can be null (=unknown). This PR replaced the switch with simple Yes/No/Unknown options.
> Support editing optional booleans

- src/pages/models/[id].tsx
I used a darker font color to make the text more readable in light mode.
> Make metadata table more readable in light mode

- src/elements/components/searchbar.tsx
- src/lib/hooks/use-search.ts
- src/pages/index.tsx
Changes:
- Immediately update results when the user presses Enter in the search bar.
- Scroll to search results on mobile after Enter.
- Fixed a bug in `useSearch` where search results were not updated quickly enough.
> Scroll to results on search enter

- data/models/1x-Anti-Aliasing.json
- data/models/1x-DeJpeg-Fatality-PlusULTRA.json
- data/models/1x-Fatality-DeBlur.json
- data/models/1x-ReFocus-Cleanly.json
- data/models/1x-ReFocus-V3.json
- data/models/1x-UnResize-V3.json
- data/models/1x-cinepak.json
- data/models/1x-mdeblur.json
- data/models/4x-Face-Ality-V1.json
- data/models/4x-Faces-04-N.json
- data/models/4x-Fatal-Anime.json
- data/models/4x-Fatal-Pixels.json
- data/models/4x-FatalimiX.json
- data/models/4x-Fatality-MK2.json
- data/models/4x-Fatality.json
owncube.com recently messed up, went down, and lost the data of a bunch of customers. [Read more about this here](https://www.reddit.com/r/NextCloud/comments/16hneg0/owncube_provider_3rd_day_of_downtime/). This unfortunately included a few of our models. Luckily, we already self-hosted all of them, so nothing was lost.
This PR removes the dead owncube links. If they ever come back online (which seems unlikely), we can revert this PR.
> Remove owncube.com links

- package-lock.json
- package.json
- src/elements/components/model-card.tsx
- src/elements/head-common.tsx
- src/lib/text-description.ts
- src/pages/models/[id].tsx
The text displayed by search engines for our model pages was pretty bad, so I added [structured data](https://blog.logrocket.com/improving-seo-rending-structured-data-react/). This allows search engines to better display our models. Hopefully, they will soon look like the search results of civitai.com.
> Add structured data for models

- src/elements/tag-selector.tsx
I messed up in #301. When I refactored how tooltips work, I didn't test the tag selector enough. So the tag selector showed "No description." for all tags with a description. This PR fixes this by simply not showing that useless tooltip.
> Fixed "No description." in tag selector

- src/lib/data-api.ts
- src/lib/server/file-data.ts
> Added in-memory collection

- src/lib/image-util.ts
- src/pages/api/fetch.ts
To fetch the HTML of a website, we need to circumvent CORS restrictions. I previously did that with `cors-anywhere.herokuapp.com`, but that service requires that you manually enable it via a button press. So I added another API route to our website that just does a fetch. This fetch doesn't have any CORS restrictions, because the NodeJS server is doing the fetching.
> More reliable HTML fetching

- package-lock.json
- package.json
- src/lib/lock.ts
I never liked my own mutex implementation, so I finally replaced it with [the `async-mutex` library](https://www.npmjs.com/package/async-mutex#what-is-it).
> Use the `async-mutex` library

- src/lib/model-props.ts
- src/pages/models/[id].tsx
Since it came up in #333, I decided to fix the problem of empty size tags. The UI will now automatically remove empty tags. The `validate-db` CI step will now also check there are no empty size tags.
> Disallow empty size tags

- src/lib/model-props.ts
Thanks to @Kim2091, all models have tags now, so I added a check that disallows models without tags. This will ensure that all models have at least one tag going forward.
> Disallow models with empty tags

- src/elements/components/editable-tags.tsx
I noticed that links for ESRGAN+ didn't work, so I fixed it.
> Fixed tag links in model page

- next.config.js
- package-lock.json
- package.json
Seems like we can't upgrade to NextJS 14. They removed support for API routes in the dev server when `output: 'export'`. So they completely dropped support for our edit mode concept. So we'll have to move out our API routes into a separate server before we can upgrade to NextJS 14 properly.
> Back to NextJS 13

- src/elements/components/editable-tags.tsx
- src/elements/tag-selector.tsx
- src/elements/tag-view.tsx
- src/lib/schema.ts
- src/lib/util.ts
- src/pages/tags.tsx
To prevent the simple tag selector from being over-crowded, I added the ability to hide tags. Hidden tags will not be shown in the simple tag selector. They will behave just like normal tags anywhere else.
In the follow screenshots, I hid a bunch of subject tags:
Editing-wise, the tag page now looks like this:
We can use the new eye button toggle the visibility of tags.
---
Note: This PR does **not** hide any tags. It only adds the functionality to hide tags.
> Add ability to hide tags in simple tag selector

- src/elements/components/image-carousel-image.tsx
Fixes the bug I mentioned in #349.
> Fixed layout bug for caption on small images

- src/elements/components/download-button.tsx
This is a pure UI change. The frontend will simply convert Google Drive file links to direct download links for the user's convenience.
> Automatically convert GDrive file links to direct download links

- src/elements/components/model-card-grid.module.scss
- src/elements/components/model-card.tsx
This PR is preparation for automated thumbnails. I changed 2 things:
- I changed the break point when the model grid transitions from 2 models to 1 model per row. This reduces the width of the model card and shows less of the thumbnail.
- I changed the scale rounding for integer scaling. Instead of rounding down at .5, we now round up at .35. This ensures that the maximum thumbnail size is now at most 1.35x that at 100% zoom instead of 1.5. This might not seem like much, but this for both width and height, so it's the difference between 1.8x file size and 2.25x file size.
> Smaller thumbnails for edge cases

- .github/workflows/frontend.yml
- .github/workflows/nextjs.yml
- .gitignore
- invoke-spandrel.py
- package.json
- scripts/generate-thumbnails.ts
- scripts/thumbnails.py
- scripts/validate-db.ts
- src/elements/components/model-card.tsx
- src/lib/model-props.ts
- src/lib/schema.ts
- src/lib/server/file-data.ts
Fixes #354
Here's what I said about the thumbnail generation on discord:
> For 412 images and a total of 453 MB, it generates 10.2 MB of thumbnails.
>
> To get them this small, I used JPEG compression a lot. All LR or SR images that are displayed without zoom are JPEG q90% compressed. All LR images that are zoomed in use PNG.
> 
> I did this because the JPEG artifacts are slight enough to not be noticeable. They might be visible on mobile (where a DPI of 300% is possible), but that's a sacrifice I'm willing to make. Of course, the LRs of 2x, 4x, 8x models are always zoomed in, so I went with PNG for them.
>
> One minor detail: I generate thumbnail for images, not for models. This has the major advantage that models that use the same (LR) images, share thumbnails. There isn't a lot of …
> Add generated thumbnails

- src/pages/models/[id].tsx
I didn't test thoroughly enough, which caused this:
I fixed this by changing the way model props are filtered. Instead of saying which props shouldn't be displayed, it should have said which props should be displayed from the start.
> Fixed thumbnail `[object Object]` on model pages

- data/models/4x-Nomos8k-span-otf-strong.json
I noticed that the links pointed to the files of Nomos8k_span_otf_medium instead.
> Fixed download links of Nomos8k_span_otf_strong

- src/elements/components/download-button.tsx
I found 2 other types of Google Drive links that could be converted into direct download links. The first are older download links and the second are open file links.
> Improved direct download link conversion

- src/elements/components/download-button.tsx
- src/lib/model-props.ts
- src/lib/schema.ts
- src/lib/sort-models.ts
This PR makes the `size` property on resources required. It has been nullable up until now because we didn't know the size of all model files in the beginning. This is no longer the case, so I think it's fine to require `size` now.
> Require resource size

- src/lib/model-props.ts
- src/lib/schema.ts
Since all models have a hash since #368, I made it a required property of all resources.
Similar to #366.
> Require SHA256 hash for all resources

- src/lib/schema.ts
I need this for an upcoming PR and those 2 types should have been exported from the beginning.
> Export file types from `schema.ts`

- scripts/thumbnails.py
- src/elements/components/model-card.tsx
- src/lib/schema.ts
This improves the thumbnail loading of non-1x models by storing the size of the LR and SR images. This allows the model card to calculate the max size before both images are fully loaded. Since the zoom of LR images is tied to that max size, this means that LR images are now always zoomed correctly from the start. This makes thumbnail loading appear a lot smoother since LR images don't suddenly zoom in anymore.
> Improved thumbnail loading

- scripts/generate-api.ts
Someone reported that tag-categories wasn't available in our API. After looking into it, I realized we manually fetch all the data out of fileApi instead of just iterating through it to generate everything available. So, I fixed that.
> Auto generate our entire JSON API based on available keys of fileApi

- data/models/2x-AnimeJaNai-HD-V3-Compact.json
- data/models/2x-AnimeJaNai-HD-V3-SuperUltraCompact.json
- data/models/2x-AnimeJaNai-HD-V3-UltraCompact.json
- docs/contributing/index.md
Adds AnimeJaNai HD V3 models to the database, and also fixes a broken link in the docs.
> Add AnimeJaNai HD V3 models

- src/lib/implied-tags.ts
- src/lib/parse-discord-message.ts
- src/lib/schema.ts
- src/pages/add-model.tsx
- src/pages/tags.tsx
- tests/search/__snapshots__/parse-discord-messages.test.ts.snap
- tests/search/parse-discord-messages.test.ts
This adds a form to automatically parse discord messages from model-releases. 
This makes adding model released on discord very easy. You basically just have to copy the message, paste it in, download the model file, select the model file, and then add the model. Most information will already be filled in. All that is left to do is to set the author, add more tags, add images (if any), and maybe clean up the description.
In the following example, I just pasted the message. See how it automatically filled out name, scale, and .pth link. The other information from the message is automatically inserted when the model is added. Some tags will also automatically be added based on the model description.
Adding the model then yields this page:
> Add form to automatically parse discord messages

- pyrightconfig.json
We have a bit of Python code, so I added a pyright config file to at least add type checking in the IDE. We can set up CI later if needed.
> Add pyright config for python script

- src/elements/components/client.tsx
- src/elements/header.tsx
Currently, every page of the website contains a copy of the header with all of its icon (OMDB logo + the other icons for links and buttons). This adds up to roughly 15KB per page, or roughly 9MB for all pages. 9MB is quite significant considering that all thumbnails combined are 10MB.
This PR addresses this issue by only rendering the full header on the client. The 15KB for the header are stored in a JS chunk that is shared between all pages. 
Since the header now needs to be loaded, users will briefly see a blank space when the OMDB logo will be. All the elements on the right side of the header also aren't loaded. This shouldn't be an issue since this only happens on their first page visit.
> Only render full header in client

- src/pages/models/[id].tsx
This PR adds a "Delete Model" button. Simple and ugly but it works.
> Add a button to delete models

- data/models/1x-span-anime-pretrain.json
This replaces the discord link of 1x-span-anime-pretrain with a self-hosted one.
> Self-host 1x-span-anime-pretrain

- src/lib/model-props.ts
Fixes #403.
I forgot to add safetensors files to list of allowed resource types in model props, which is used for validation.
Thanks for reporting @Phhofm!
> Fixed validation for safetensors files

- src/lib/model-props.ts
Fixes a bug introduced in #407 that caused the validation to forget about external data.
> Fixed validation forgetting about external data

- src/pages/models/[id].tsx
I noticed it was non-obvious where tags are supposed to be edited from since they aren't labeled and are just a button when adding a model that has no tags yet, so I added a little label for when in edit mode.
> Add tags label in edit mode

- scripts/model-from-issue.py
Made a simple crappy python script where you give it an issue number and it dumps the info as a model file. While it wasn't particularly difficult to add the requests to begin with, this should just help save a step or two.
This can also now dump all open model add request issues at once.
> Add script for converting a model request issue into a model file

- data/models/2x-AoMR-mosr.json
- data/models/4x-2xAoMR-mosr.json
- data/models/4x-DRCT-L.json
- data/models/4x-Nomos2-hq-atd.json
- data/models/4x-Nomos2-hq-drct-l.json
- data/models/4x-PurePhoto-RealPLSKR.json
- data/users.json
Models being added:
4xNomos2_hq_atd
4xNomos2_hq_drct-l (plus its official pretrain from the drct repo, 4x-DRCT-L)
2xAoMR_mosr
I also checked the issued and added the model requests in issue #459  :
4xPurePhoto-RealPLSKR
> Adding some more models

- data/models/2x-LiveActionV1-SPAN.json
- data/users.json
Add my SPAN model for live action video (https://github.com/jcj83429/upscaling/tree/4a9cae54ebaccbd51be1f7b7051ec39a0b1d6a8a/2xLiveActionV1_SPAN)
> Add 2xLiveActionV1_SPAN
